name: Run Slicer Module Tests

# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches: [main]

jobs:
  # Job 1: Slicer module tests (requires Slicer Python environment but no GUI)
  test-slicer-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Slicer
        run: |
          # Download and install Slicer 5.8.1
          wget https://download.slicer.org/bitstream/67c51fc129825655577cfee9 -O Slicer-5.8.1-linux-amd64.tar.gz
          tar xzvf Slicer-5.8.1-linux-amd64.tar.gz
          export SLICER_HOME=$PWD/Slicer-5.8.1-linux-amd64
          echo "SLICER_HOME=$SLICER_HOME" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install module into Slicer
        run: |
          make install-module

      - name: Run Slicer module tests
        run: |
          make test-slicer-modules

      - name: Upload Slicer module test coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: slicer-modules
          name: codecov-slicer-modules
          fail_ci_if_error: false

  # Job 2: Pure Python tests (fastest, no Slicer modules required)
  test-py-slicer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Slicer
        run: |
          # Download and install Slicer 5.8.1
          wget https://download.slicer.org/bitstream/67c51fc129825655577cfee9 -O Slicer-5.8.1-linux-amd64.tar.gz
          tar xzvf Slicer-5.8.1-linux-amd64.tar.gz
          export SLICER_HOME=$PWD/Slicer-5.8.1-linux-amd64
          echo "SLICER_HOME=$SLICER_HOME" >> $GITHUB_ENV

      - name: Install test dependencies in Slicer Python
        run: |
          make install-test-deps

      - name: Run pure Python tests
        run: |
          make test-py-slicer

      - name: Upload pure Python test coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: py-slicer
          name: codecov-py-slicer
          fail_ci_if_error: false

  # Job 3: Tests with coverage (most comprehensive, skips GUI tests)
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Slicer
        run: |
          # Download and install Slicer 5.8.1
          wget https://download.slicer.org/bitstream/67c51fc129825655577cfee9 -O Slicer-5.8.1-linux-amd64.tar.gz
          tar xzvf Slicer-5.8.1-linux-amd64.tar.gz
          export SLICER_HOME=$PWD/Slicer-5.8.1-linux-amd64
          echo "SLICER_HOME=$SLICER_HOME" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install module into Slicer
        run: |
          make install-module

      - name: Run coverage tests
        run: |
          make test-coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: coverage
          name: codecov-coverage
          fail_ci_if_error: false
