name: Run Slicer Module Tests

# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches: [main]

jobs:
  # Job 1: Pure Python tests (fastest, no Slicer modules required)
  test-py-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install test dependencies in system Python
        run: |
          pip install pytest pytest-cov pytest-mock hypothesis

      - name: Run pure Python tests
        run: |
          find . -type d -name tests -not -path "./.venv/*" -not -path "./build/*" -not -path "./__pycache__/*" | xargs -I {} python -m pytest {}

      - name: Upload pure Python test coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: py-system
          name: codecov-py-system
          fail_ci_if_error: false
