name: Build and Test Slicer Extension (Official)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git

      - name: Download Slicer
        run: |
          # Download Slicer for testing (not building)
          SLICER_VERSION="5.8.1"
          SLICER_URL="https://download.slicer.org/bitstream/67c51fc129825655577cfee9"
          wget $SLICER_URL -O Slicer-$SLICER_VERSION-linux-amd64.tar.gz
          tar xzf Slicer-$SLICER_VERSION-linux-amd64.tar.gz
          export SLICER_HOME=$PWD/Slicer-$SLICER_VERSION-linux-amd64
          echo "SLICER_HOME=$SLICER_HOME" >> $GITHUB_ENV

      - name: Verify module structure
        run: |
          # Verify that the modules exist in the source tree
          modules=("AnnotateUltrasound" "AnonymizeUltrasound" "MmodeAnalysis" "TimeSeriesAnnotation")
          for module in "${modules[@]}"; do
            if [ -d "$module" ]; then
              echo "✓ Found $module in source tree"
              ls -la "$module"
            else
              echo "✗ Module $module not found in source tree"
              exit 1
            fi
          done
          echo "✓ All modules present in source tree"

      - name: Run Python tests
        run: |
          # Run pytest tests in Slicer's Python environment
          make test-pytest

      - name: Run GUI tests with additional paths
        run: |
          # Set up display for GUI tests
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

          # Run GUI tests using the additional module path approach
          $SLICER_HOME/bin/Slicer --no-main-window --python-script AnnotateUltrasound/Testing/Python/AnnotateUltrasoundGUITest.py
