name: Build and Test Slicer Extension (Official)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and test extension (official Slicer CI)
        uses: Slicer/SlicerExtension-Linux-CI@v1
        with:
          slicer_version: "5.8.1"
